# Generated by Django 4.0.5 on 2022-08-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1995-03-27'),
            preserve_default=False,
        ),
    ]
